# Generated by Django 2.2 on 2023-01-05 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0005_delete_compareitem_delete_compareproject_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='groceries',
            table='groceries',
        ),
    ]
